apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - target:
      kind: StorageClass
      name: local-path
    patch: |-
      - op: replace
        path: /metadata/annotations
        value:
          storageclass.kubernetes.io/is-default-class: "false"
