apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-HelmChartConfig.yaml
    target:
      kind: HelmChartConfig
      name: rke2-ingress-nginx
  - path: patch-service.yaml
    target:
      kind: Service
      name: kube-api-lb
