---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      service:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.io/address-pool: apps-pool
        loadBalancerIP: "10.10.10.98"
      ingressClassResource:
        default: true
      extraArgs:
        default-ssl-certificate: "kube-system/apps-wildcard-tls"
