---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      service:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/address-pool: apps-pool
        loadBalancerIP: "10.10.10.98"
      ingressClassResource:
        default: true
---
apiVersion: v1
kind: Service
metadata:
  name: kube-api-lb
  namespace: kube-system
  annotations:
    metallb.universe.tf/address-pool: api-pool
spec:
  type: LoadBalancer
  loadBalancerIP: "10.10.10.99"
  selector:
    component: kube-apiserver
  ports:
  - name: https
    port: 6443
    targetPort: 6443
    protocol: TCP
