---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: smtp-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kub01/smtp
        property: password
