apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ExternalSecret
      name: smtp-credentials
    patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: kub01/smtp
