---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # OLM CRDs und Core Installation
  - https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/d3afe92560091f35adbb4d1d2d07e7a7dee7f12e/deploy/upstream/quickstart/crds.yaml
  - https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/d3afe92560091f35adbb4d1d2d07e7a7dee7f12e/deploy/upstream/quickstart/olm.yaml
